Update readme instructions regarding installation
redhat-developer/opencompose pull request #111
Opened 2017-04-19 16:33 UTC by cdrage

Updates the readme for how to install Kompose correctly.

2017-04-20 15:43 UTC, pradeepto requested changes

2017-04-20 15:43 UTC, pradeepto commented on README.md
> +# Linux
@cdrage These don't render correctly. The # Linux breaks it, at least in the preview mode. Same applies below as well.

2017-04-20 15:51 UTC, surajnarwade commented on README.md
> +# Linux
one  backtick character is missing on line 23, that's why its breaking

2017-04-20 15:51 UTC, surajnarwade commented on README.md
> +# Linux
one backtick character is missing on line 23, that's why its breaking

2017-04-20 15:57 UTC, cdrage commented on README.md
> +# Linux
Woops. I'll quickly fix that.

2017-04-20 15:57 UTC, cdrage commented
@pradeepto @surajnarwade Done. Ready for another quick review.

2017-04-21 05:42 UTC, surajssd commented
cool this LGTM!

2017-04-21 05:42 UTC, merged

2017-04-25 07:19 UTC, kadel commented on README.md
> +curl -L https://github.com/redhat-developer/opencompose/releases/download/v0.1.0/opencompose-windows-amd64.exe -o opencompose.exe
curl on windows?

2017-04-25 13:39 UTC, cdrage commented on README.md
> +curl -L https://github.com/redhat-developer/opencompose/releases/download/v0.1.0/opencompose-windows-amd64.exe -o opencompose.exe
According to `kubectl`, yup. Binary installation, works well.