WIP - reference for opencompose file
redhat-developer/opencompose pull request #15
Opened 2017-02-17 13:05 UTC by kadel

I've started documenting  OpenCompose yaml file structure.

It  is  really rough draft, but I'm putting it here because I could use some help with cleanly explaining some concepts in OpenCompose file.

2017-02-17 13:07 UTC, kadel commented on docs/reference.md
> +- `HostPort`
I don't know how to describe this ideally in one sentence :-(

2017-02-20 14:58 UTC, tnozicka approved these changes

2017-02-20 15:22 UTC, tnozicka requested changes

2017-02-20 15:22 UTC, tnozicka commented on docs/file-reference.md
> +OpenCompose file has two main sections version and services.
make `version` and `services` in italic or highlight them in some way

2017-02-20 15:23 UTC, kadel commented on docs/file-reference.md
> +  port: 8080:8088:80
this should be just `8080:80`

2017-02-21 09:56 UTC, tnozicka requested changes

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +`services` is main section that lists all the services that this OpenCompose files describes.
s/files/file/

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +One service can be comprised of multiple containers.
How about: 
Describes one service. Service can be composed of one or multiple containers which are scheduled together and can communicate using localhost. (They share TCP/IP stack.)

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +  - <ContainerSpec>
I think one item is enough since this is an array, but I don't have strong opinion on this.

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +OpenCompose format version
mention here it's a string

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +    - -bar
This double dash thing seems suspicious although it should be a valid syntax. Can we put something nice here like `- "--file"` `- "filename"`

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +ContainerSpec describes one container - how container is started, what and how are ports exposed.
ContainerSpec describes an image to use, its arguments, which ports should be exposed and how.

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> + You can find more about it [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/container-command-args/)
s/about it/about it in/

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +This is command run by the container.
s/This is c/Command/

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +`ServicePort` is optional. If is same as `ContainerPort` if not specified.
`ServicePort` is optional. It defaults to `ContainerPort` if not specified.

2017-02-21 09:56 UTC, tnozicka commented on docs/file-reference.md
> +This is string in following format: `ContainerPort:ServicePort`
s/is string/is a string/

2017-02-21 17:04 UTC, kadel commented
updated according to comments

2017-02-22 10:23 UTC, kadel commented
ping @pradeepto

2017-02-22 11:23 UTC, pradeepto commented
@kadel Putting this in my queue. Will get on it asap (ideally today).

2017-02-22 11:34 UTC, kadel commented
> @kadel Putting this in my queue. Will get on it asap (ideally today).

No worries, just wasn't sure if you noticed it ;-)

2017-02-22 11:45 UTC, tnozicka commented on docs/file-reference.md
> +together and can communicate using localhost. (Containers in the same service share network namespace)
s/)/.)/

2017-02-22 11:45 UTC, tnozicka commented on docs/file-reference.md
> +`services` has to be array of [ServiceSpec](#servicespec)
s/)/)./

2017-02-22 11:45 UTC, tnozicka commented on docs/file-reference.md
> +ContainerSpec describes an image to use, its arguments and which ports should be exposed and how.
2 `and` seem strange
s/arguments and/arguments,/

2017-02-22 12:58 UTC, kadel commented
updated

2017-02-22 13:08 UTC, tnozicka approved these changes

2017-02-24 12:35 UTC, tnozicka requested changes

2017-02-24 12:35 UTC, tnozicka commented on docs/file-reference.md
> +|string|    no    | `internal` or `external`|
enum (string)

2017-02-24 12:35 UTC, tnozicka commented on docs/file-reference.md
> +If `type` is `internal` than port will be accessible only by other containers inside Kubernetes cluster
You are missing a description for the case when `type` is not specified.

How about putting it into a table? [type, description] (\<unspecified\>, internal, external)

2017-02-24 12:44 UTC, tnozicka commented on docs/file-reference.md
> +If `type` is `external` than port will be accessible by other service outside Kubernetes cluster
s/by other service //

2017-02-24 12:44 UTC, tnozicka commented on docs/file-reference.md
> +If `type` is `internal` than port will be accessible only by other containers inside Kubernetes cluster
s/by other containers // ?

2017-02-24 13:37 UTC, tnozicka approved these changes
lgmt

2017-02-24 13:56 UTC, merged