`stdout` will be printed if no option for output is specified
redhat-developer/opencompose pull request #155
Opened 2017-06-02 10:21 UTC by surajnarwade

Resolves #80

2017-06-02 10:55 UTC, kadel commented on pkg/cmd/convert.go
> +	if outputDir == "./" {
it shouldn't be done like this.
It breaks `opencompose convert -o -`

2017-06-05 05:31 UTC, surajnarwade commented
@kadel, 

```
$ opencompose convert -f hello-nginx.yml -o .
created file "helloworld-service.yaml"
created file "helloworld-deployment.yaml"
```

it's working :)

2017-06-05 06:38 UTC, surajssd commented
@surajnarwade please update the commit message and title of the PR as well, it is very confusing what change this PR adds.

These might help you:
- https://chris.beams.io/posts/git-commit/
- http://conventionalcommits.org/

2017-06-05 06:39 UTC, surajssd commented
I always refer those before I send a PR! :-)

2017-06-05 06:51 UTC, surajssd requested changes

2017-06-05 06:51 UTC, surajssd commented on pkg/cmd/convert.go
> +	if outputDir == "./" {
This is printing to cmd line even when I give current directory as shown below:
```bash
✔ ~/go/src/github.com/redhat-developer/opencompose/examples/wordpress [pr_155 L|✔] 
12:19 $ opencompose version
v0.2.0+0893f80-clean

✔ ~/go/src/github.com/redhat-developer/opencompose/examples/wordpress [pr_155 L|✔] 
12:19 $ opencompose convert -f storage.yaml -o ./                                                                                                                     
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
...
```

2017-06-05 07:33 UTC, containscafeine commented
@surajnarwade yep, the commit message is unclear, please include an example in the commit message that what was the previous behavior and what is the new behavior.
Also, we need some tests for this -
- `opencompose convert` prints to STDOUT
- `opencompose convert -o -` throws an error
- `opencompose convert -o .` saves to `pwd`
- `opencompose convert -o ./` saves to `pwd`
- `opencompose convert -o /tmp/` saves to `/tmp/`

2017-06-05 07:34 UTC, concaf requested changes
@surajnarwade yep, the commit message is unclear, please include an example in the commit message that what was the previous behavior and what is the new behavior.
Also, we need some tests for this -
- `opencompose convert` prints to STDOUT
- `opencompose convert -o -` throws an error
- `opencompose convert -o .` saves to `pwd`
- `opencompose convert -o ./` saves to `pwd`
- `opencompose convert -o /tmp/` saves to `/tmp/`

2017-06-06 14:19 UTC, surajnarwade commented
@kadel @surajssd @containscafeine needs review for this

2017-06-06 14:47 UTC, kadel approved these changes

2017-06-08 08:23 UTC, concaf approved these changes

2017-06-08 08:24 UTC, merged