Add Contact section to README
redhat-developer/opencompose pull request #46
Opened 2017-03-03 18:02 UTC by tnozicka

Now we have ML and Slack (with IRC Bridge).

2017-03-03 18:42 UTC, pradeepto requested changes

2017-03-03 18:42 UTC, pradeepto commented on README.md
> +[opencompose.slack.com](https://opencompose.slack.com)
Let's not do this please. We should talk on sig-apps on Kubernetes slack instead. If and when time comes, we should get our own channel on the same slack.

2017-03-03 19:22 UTC, tnozicka commented on README.md
> +[opencompose.slack.com](https://opencompose.slack.com)
I think we should have both. There should be a channel for discussing the tool, helping users, ... And we should also talk on #sig-apps when we want to engage Kubernetes community; on topics that relate to them. I don't think that spamming #sig-apps with discussing bugs, technological discussions and others would do any good.

2017-03-06 10:44 UTC, kadel commented on README.md
> +[opencompose.slack.com](https://opencompose.slack.com)
I'm not sure about slack either :-(

1) It is not working as you described ;-) Users need invitation first to sign up to opencompose slack.

2) Isn't ML enough for now?

2017-03-06 11:45 UTC, tnozicka commented on README.md
> +[opencompose.slack.com](https://opencompose.slack.com)
Ok, Slack sucks. I'll leave only ML and #sig-apps for now.

2017-03-06 12:27 UTC, tnozicka commented
@pradeepto @kadel fixed

2017-03-06 12:50 UTC, pradeepto approved these changes

2017-03-06 12:51 UTC, pradeepto commented
LGTM

2017-03-06 12:54 UTC, merged