[WIP] implement service level labels
redhat-developer/opencompose pull request #82
Opened 2017-03-27 15:37 UTC by containscafeine

Fixes #23

2017-04-04 11:46 UTC, surajssd commented on pkg/object/object.go
> +	Labels     Label
in object.go all the types are made of builtin types as opposed to ones like this! I think @tnozicka can shade more light on it!

2017-04-04 11:53 UTC, surajssd commented on pkg/object/object.go
> +type Label map[string]string
Move this definition in `encoding.go`

2017-04-04 11:59 UTC, surajssd commented on pkg/transform/kubernetes/kubernetes.go
> +				transformerUtil.ApplyOpenComposeLabelsToProvider(&service.Labels, &t.ObjectMeta.Labels)
I don't know a better way of doing this, the only problem with this method is that it causes problems like we had in kompose. If new k8s object generation support is added and if label application is not done here for that object we now have inconsistent objects generated, which is again hard to test.

If there is an alternate generic method to do this I would love to see that, which wil save us from mistakes in future.

2017-04-04 12:05 UTC, surajssd commented on pkg/transform/kubernetes/kubernetes.go
> +				transformerUtil.ApplyOpenComposeLabelsToProvider(&service.Labels, &t.ObjectMeta.Labels)
Even if we need to do this we need to design it in such a way that every k8s object should satisfy some form of interface that applies labels.

2017-04-05 13:09 UTC, kadel commented on pkg/object/object.go
> +type Label map[string]string
This should be here, that is correct.
But just rename it to `Labels`, so it reflects that this holds multiple labels.

2017-04-05 13:09 UTC, kadel commented on pkg/object/object.go
> +	Labels     Label
I think this is correct.

2017-04-05 13:09 UTC, kadel commented on pkg/encoding/v1/encoding.go
> +type Label map[string]string
this should reference `Label` type  from object package.
`type Label object.Label`

2017-04-05 13:45 UTC, kadel commented on pkg/transform/kubernetes/kubernetes.go
> +				transformerUtil.ApplyOpenComposeLabelsToProvider(&service.Labels, &t.ObjectMeta.Labels)
I think that adding lables to objects should be handled in functions that are responsible for creating those objects. eg `CreateServices` and `CreateDeployments`

2017-04-05 15:43 UTC, containscafeine commented on pkg/encoding/v1/encoding.go
> +type Label map[string]string
fixed

2017-04-05 15:44 UTC, containscafeine commented on pkg/object/object.go
> +type Label map[string]string
renamed

2017-04-06 07:53 UTC, containscafeine commented on pkg/transform/kubernetes/kubernetes.go
> +				transformerUtil.ApplyOpenComposeLabelsToProvider(&service.Labels, &t.ObjectMeta.Labels)
moved to `Create*` methods

2017-04-06 12:31 UTC, kadel commented
Don't forget about labels in `PodTemplateSpec` inside Deployment. This label should be propagated down to Pod level.

2017-04-11 11:44 UTC, surajssd commented
for validating if the label value is right you can use the validation function [`IsValidLabelValue`](https://github.com/redhat-developer/opencompose/blob/master/vendor/k8s.io/client-go/pkg/util/validation/validation.go#L77), use this because there is a [doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/identifiers.md) that specifies what qualifies as a label and what does not.

2017-04-13 10:22 UTC, containscafeine commented
@surajssd thanks for pointing that out :+1: 

I have added the validation, validation tests, tests in encoding_test.go, PTAL!
@surajssd @kadel

2017-04-13 13:27 UTC, kadel reviewed
two small changes, otherwise lgtm

2017-04-13 13:27 UTC, kadel commented on pkg/transform/kubernetes/kubernetes.go
> +					Labels: *util.MergeMaps(
I would swap order of parameters here.
```
*util.MergeMaps(
  &serviceLabels,
  &map[string]string{"service": o.Name}
),
```

Map with "service" label should be the last as it should never be overwritten.
Its used as selector for Service and other stuff.

I would also add comment explaining that it has to be last and why is that.

Same thing in other places setting Labels

2017-04-13 13:27 UTC, kadel commented on pkg/encoding/v1/encoding_test.go
> +			"Providing valid label strings",
You are testing whole service here.

You should add test testing `(lb *Labels) UnmarshalYAML` something like  `TestLabels_UnmarshalYAML` similar to `TestEnvVariable_UnmarshalYAML` and others.

2017-04-18 05:55 UTC, containscafeine commented on pkg/transform/kubernetes/kubernetes.go
> +					Labels: *util.MergeMaps(
Totally missed this somehow, fixed now. Thanks for pointing it out.

2017-04-18 08:52 UTC, containscafeine commented on pkg/encoding/v1/encoding_test.go
> +			"Providing valid label strings",
fixed

2017-04-19 16:15 UTC, surajssd commented on pkg/encoding/v1/encoding_test.go
> +		for _, tt := range tests {
gofmt error?

2017-04-26 12:21 UTC, containscafeine commented on pkg/encoding/v1/encoding_test.go
> +		for _, tt := range tests {
yep, fixed, thanks

2017-05-05 07:09 UTC, surajssd commented on pkg/util/util.go
> +// TODO: add to docs about use with caution bits
where do you wanna add those docs to?

2017-05-05 07:12 UTC, surajssd commented on pkg/util/util.go
> +// In case of conflicting keys, the map that is provided later wins.
nit: how about `In case of conflicting keys, the map that is provided later overrides the previous one` ?

2017-05-05 08:43 UTC, surajssd requested changes
Add docs about the support of this in the [file ref](https://github.com/redhat-developer/opencompose/blob/master/docs/file-reference.md). Also add an example of this in examples folder.

2017-05-05 08:57 UTC, surajssd commented
Functionality wise this works for me, @containscafeine apart from the changes requested rest LGTM

2017-05-05 10:17 UTC, kadel commented
> Add docs about the support of this in the file ref. Also add an example of this in examples folder.

Just small note. All files in examples folder should work and do something meaningful.

2017-05-08 05:55 UTC, containscafeine commented
- [ ] rebase

2017-05-15 14:37 UTC, containscafeine commented on pkg/util/util.go
> +// TODO: add to docs about use with caution bits
to the developer docs, once and when we have it :)

2017-05-15 14:38 UTC, containscafeine commented on pkg/util/util.go
> +// In case of conflicting keys, the map that is provided later wins.
ack, fixed

2017-05-15 15:51 UTC, surajssd approved these changes

2017-05-15 15:52 UTC, surajssd commented
cool this LGTM

2017-05-17 13:56 UTC, merged